# Generated by Django 3.0.7 on 2021-12-14 10:46

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taxAPI.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('service', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('expire_date', models.DateField(default=taxAPI.models.a_month_from_now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'PAID'), (2, 'EXPIRED')], default=0)),
                ('barcode', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('CD', 'Credit Card'), ('DC', 'Debit Card'), ('CA', 'Cash')], max_length=2)),
                ('card_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999999999), django.core.validators.MinValueValidator(1000000000000000)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('paid_date', models.DateField(default=datetime.date.today)),
                ('code_bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxAPI.Payable')),
            ],
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['service'], name='taxAPI_paya_service_601c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['status'], name='taxAPI_paya_status_50fce0_idx'),
        ),
    ]
