# Generated by Django 3.0.7 on 2021-12-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='code_bar',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
