# Generated by Django 3.0.7 on 2021-12-14 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxAPI', '0002_auto_20211214_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='card_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='code_bar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxAPI.Payable'),
        ),
    ]
